name: Banners for the Tribes of Israel
favicon: null
layout_spectrum: 0
typography_spectrum: 0.76152
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#060503'
    - '#b2b1b7'
    - '#007da6'
    - '#bc415e'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
