name: Israel Banners
favicon: null
layout_spectrum: 0.50226
typography_spectrum: 0.50136
title: Banners for the Tribes of Israel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#232122'
    - '#ff0000'
    - '#fea74c'
    - '#4fbbcf'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
