name: Banners for the Tribes of Israel
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6872004675678909
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0.4889422438573092
  rhythmicContrast: 0.377128902124241
purpose: []
