name: Banners for the Tribes of Israel
favicon: null
layout_spectrum: 0
typography_spectrum: 0.50136
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#232122'
    - '#ff0000'
    - '#fea74c'
    - '#4fbbcf'
  brandStrength: 0
  lightness: 0.875
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
