name: Banners for the Tribes of Israel
favicon: null
layout_spectrum: 0
typography_spectrum: 0.76152
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff0000'
    - '#252224'
    - '#ff4175'
    - '#66cbcd'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
